### ISSUE TITLE
SFX fails to load on Windows 10 1703

### ISSUE THREAD

**Issue by chrislake** [chrislake/7zsfxmm#1]
On the latest Windows 10 1703 release, the SFX from the site fails to start, nothing, not even a crash dump to investigate. However, if I use windbg.exe, depends.exe or Visual Studio (2017 community), to run the SFX then all works well.

I successfully managed to compile the 7zsd_All_x64.sfx from source (build 1.7.0.3900) and started to look at the problem by adding a MessageBoxA() call in to WinMain, but it seems that it doesn't even get that far as the message box is not displayed.

Using Process Monitor, the best I have been able to see is that it fails just prior to loading the oleacc.dll, though why only on actual execution as opposed to when run with windbg etc. I have no idea.

**Comment by chrislake** [comment]
OK, found the point of failure. In `7zSfxMod/sources/exceptions.cpp` line 117:

    AddVectoredExceptionHandler( 0, ExceptionHandler );

Fails. If I add a `MessageBoxA` prior to the call, it works. If I add a try-catch around the call, no error seems to be thrown, but it never gets to a `MessageBoxA` after the call.

Further investigation shows that simple existence of line 86:

    ExitProcess( ERRC_EXCEPTION );

Causes the problem. Commenting that line out the dialog messages expected are shown.

**Comment by chrislake** [comment]
In the end, simply ignoring the new DBG_PRINTEXCEPTION_WIDE_C (and possibly existing DBG_PRINTEXCEPTION_C) is enough to fix the issue.

**Comment by Ander73** [comment]
7zsfx_x64 cause the porblem, error message: Fail Fast  bla-bla
7zsfx_x86 - all right.
